/* 
  CONVENCIONES 
  TABLAS DE MAS DE 2 PALABRAS SE UTILIZAN LAS 3 PRIMERAS LETRAS DE CADA PALABRA PARA LA LLAVE PRIMARIA  
  PARA LAS LLAVES FORANEAS SE UTILIZA LA SIGUIENTE SINTAXIS (CAMBIAR LO QUE ESTA EN MINUSCULA):
  FK_nombreTablaForanea_EN_TablaActual  
*/

CREATE TABLE CIUDAD (
CIUDAD_ID VARCHAR2 (20) NOT NULL,
NOMBRE_CIUDAD VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_CIUDAD PRIMARY KEY (CIUDAD_ID)
);
COMMENT ON TABLE CIUDAD IS 'Es la entidad que contiene los datos de las ciudades normalizadas.';
COMMENT ON COLUMN CIUDAD.CIUDAD_ID IS 'Es la la llave primaria de la tabla ciudad';
COMMENT ON COLUMN CIUDAD.NOMBRE_CIUDAD IS 'Es el nombre de la ciudad';

CREATE TABLE DIRECCION(
DIRECCION_ID VARCHAR2 (20) NOT NULL,
CALLE VARCHAR2 (3) NOT NULL,
CARRERA VARCHAR2 (3) NOT NULL,
NUMERO VARCHAR2 (3) NOT NULL,
ID_CIUDAD VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_DIRECCION PRIMARY KEY (DIRECCION_ID ),
CONSTRAINT FK_CIUDAD_EN_DIRECCION FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (CIUDAD_ID) 
);
COMMENT ON TABLE DIRECCION IS 'Es la entidad que contiene los datos de las direcciones normalizadas.';
COMMENT ON COLUMN DIRECCION.DIRECCION_ID IS 'Es la la llave primaria de la tabla direccion';
COMMENT ON COLUMN DIRECCION.CALLE IS 'Es la calle normalizada de la direccion';
COMMENT ON COLUMN DIRECCION.CARRERA IS 'Es la carrera normalizada de la direccion';
COMMENT ON COLUMN DIRECCION.NUMERO IS 'Es el numero normalizado de la direccion';
COMMENT ON COLUMN DIRECCION.ID_CIUDAD IS 'Es la llave foranea que identifica la ciudad a la cual pertenece esa direccion.';

CREATE TABLE UNIVERSIDAD (
UNIVERSIDAD_ID VARCHAR2 (20) NOT NULL,
NOMBRE_UNIVERSIDAD VARCHAR2 (50) NOT NULL,
ID_DIRECCION VARCHAR2 (20) NOT NULL UNIQUE,
CONSTRAINT PK_UNIVERSIDAD PRIMARY KEY (UNIVERSIDAD_ID),
CONSTRAINT FK_DIRECCION_EN_UNIVERSIDAD FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (DIRECCION_ID)
);
COMMENT ON TABLE UNIVERSIDAD IS 'Es la entidad que contiene los datos de las universidades normalizadas.';
COMMENT ON COLUMN UNIVERSIDAD.UNIVERSIDAD_ID IS 'Es la la llave primaria de la tabla universidad';
COMMENT ON COLUMN UNIVERSIDAD.NOMBRE_UNIVERSIDAD IS 'Es el nombre de la universidad';
COMMENT ON COLUMN UNIVERSIDAD.ID_DIRECCION IS 'Es la llave foranea que identifica la direccion unica para la universidad.';

CREATE TABLE FACULTAD (
FACULTAD_ID VARCHAR2 (20) NOT NULL,
NOMBRE_FACULTAD VARCHAR2 (50) NOT NULL,
ID_UNIVERSIDAD VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_FACULTAD PRIMARY KEY (FACULTAD_ID),
CONSTRAINT FK_FACULTAD_EN_UNIVERSIDAD FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (UNIVERSIDAD_ID) 
);
COMMENT ON TABLE FACULTAD IS 'Es la entidad que contiene los datos de las facultades que tiene una universidad normalizadas.';
COMMENT ON COLUMN FACULTAD.FACULTAD_ID IS 'Es la la llave primaria de la tabla facultad';
COMMENT ON COLUMN FACULTAD.NOMBRE_FACULTAD IS 'Es el nombre de la facultad';
COMMENT ON COLUMN FACULTAD.ID_UNIVERSIDAD IS 'Es la llave foranea que identifica la universidad a la cual pertenece la facultad';

CREATE TABLE SECRETARIA(
SECRETARIA_ID VARCHAR2 (20) NOT NULL,
NOMBRE_SECRETARIA VARCHAR2 (35) NOT NULL,
APELLIDO_SECRETARIA VARCHAR2 (35) NOT NULL,
TELEFONO_SECRETARIA VARCHAR2 (20) NOT NULL,
PASSWORD_SECRETARIA VARCHAR2(255) NOT NULL,
CONSTRAINT PK_SECRETARIA PRIMARY KEY (SECRETARIA_ID)
);
COMMENT ON TABLE SECRETARIA IS 'Es la entidad que contiene los datos de la tabla secretaria.';
COMMENT ON COLUMN SECRETARIA.SECRETARIA_ID IS 'Es la la llave primaria de la tabla secretaria.';
COMMENT ON COLUMN SECRETARIA.NOMBRE_SECRETARIA IS 'Es el nombre de la secretaria.';
COMMENT ON COLUMN SECRETARIA.APELLIDO_SECRETARIA IS 'Es el apellido de la secretaria.';
COMMENT ON COLUMN SECRETARIA.TELEFONO_SECRETARIA IS 'Es el numero de telefono fijo o celular de la secretaria.';
COMMENT ON COLUMN SECRETARIA.PASSWORD_SECRETARIA IS 'Es el password de la secretaria para poder iniciar sesi?n.';

CREATE TABLE CONSEJO_CURRICULAR(
CONSEJO_CURRICULAR_ID VARCHAR2 (20) NOT NULL,
ID_SECRETARIA VARCHAR2 (20) NOT NULL UNIQUE,
CONSTRAINT PK_CONSEJO_CURRICULAR PRIMARY KEY (CONSEJO_CURRICULAR_ID),
CONSTRAINT FK_SECRETARIA_EN_CONSEJO FOREIGN KEY (ID_SECRETARIA) REFERENCES SECRETARIA (SECRETARIA_ID) 
);
COMMENT ON TABLE CONSEJO_CURRICULAR IS 'Es la entidad que contiene los datos de la tabla consejo curricular.';
COMMENT ON COLUMN CONSEJO_CURRICULAR.CONSEJO_CURRICULAR_ID IS 'Es la la llave primaria de la tabla consejo curricular';
COMMENT ON COLUMN CONSEJO_CURRICULAR.ID_SECRETARIA IS 'Es la llave foranea que identifica la secretaria adscrita al consejo curricular, es unica';

CREATE TABLE AREA (
AREA_ID VARCHAR2 (20) NOT NULL,
NOMBRE_AREA VARCHAR2 (50) NOT NULL,
CONSTRAINT PK_AREA PRIMARY KEY (AREA_ID)
);
COMMENT ON TABLE AREA IS 'Es la entidad que contiene los datos de las areas a la cual pertenecen los solictantes.';
COMMENT ON COLUMN AREA.AREA_ID IS 'Es la la llave primaria de la tabla area';
COMMENT ON COLUMN AREA.NOMBRE_AREA IS 'Es el nombre del area';

CREATE TABLE CARGO(
CARGO_ID VARCHAR2 (20) NOT NULL,
NOMBRE_CARGO VARCHAR2 (50) NOT NULL,
CONSTRAINT PK_CARGO PRIMARY KEY (CARGO_ID)
);
COMMENT ON TABLE CARGO IS 'Es la entidad que contiene los datos de los cargos que tienen los solictantes.';
COMMENT ON COLUMN CARGO.CARGO_ID IS 'Es la la llave primaria de la tabla cargo';
COMMENT ON COLUMN CARGO.NOMBRE_CARGO IS 'Es el nombre del cargo';

CREATE TABLE PROGRAMA_ACADEMICO (
PROGRAMA_ACADEMICO_ID VARCHAR2 (20) NOT NULL,
NOMBRE_PROGRAMA VARCHAR (255) NOT NULL,
ID_FACULTAD VARCHAR2 (20) NOT NULL,
ID_CONSEJO_CURRICULAR VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_PROGRAMA_ACADEMICO PRIMARY KEY (PROGRAMA_ACADEMICO_ID),
CONSTRAINT FK_FAC_EN_PROG FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTAD (FACULTAD_ID),
CONSTRAINT FK_CON_CUR_EN_PROG FOREIGN KEY (ID_CONSEJO_CURRICULAR) REFERENCES CONSEJO_CURRICULAR(CONSEJO_CURRICULAR_ID)
);
COMMENT ON TABLE PROGRAMA_ACADEMICO IS 'Es la entidad que contiene los datos del programa academico de una facultad';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.PROGRAMA_ACADEMICO_ID IS 'Es la llave primaria de la tabla programa acad?mico.';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.NOMBRE_PROGRAMA IS 'Es el nombre del programa acad?mico.';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.ID_FACULTAD IS 'Es la llave foranea que identifica la facultad a la cual pertenece el programa.';
COMMENT ON COLUMN PROGRAMA_ACADEMICO.ID_CONSEJO_CURRICULAR IS 'Es la llave foranea que identifica el consejo curricular al cual pertenece el programa.';

CREATE TABLE SOLICITANTE(
SOLICITANTE_ID VARCHAR2 (20) NOT NULL,
NOMBRE_SOLICITANTE VARCHAR2 (35) NOT NULL,
APELLIDO_SOLICITANTE VARCHAR2 (35) NOT NULL,
TELEFONO_SOLICITANTE VARCHAR2 (20) NOT NULL,
PASSWORD_SOLICITANTE VARCHAR2(255) NOT NULL,
ID_DIRECCION VARCHAR2 (20) NOT NULL,
ID_CARGO VARCHAR2 (20) NOT NULL,
ID_AREA VARCHAR2 (20) NOT NULL,
ID_CONSEJO_CURRICULAR VARCHAR2 (20),
ID_PROGRAMA_ACADEMICO VARCHAR2 (20) NOT NULL,
  CONSTRAINT PK_SOLICITANTE PRIMARY KEY (SOLICITANTE_ID),
  CONSTRAINT FK_DIRECCION_EN_SOLICITANTE FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (DIRECCION_ID),
  CONSTRAINT FK_CARGO_EN_SOLICITANTE FOREIGN KEY (ID_CARGO) REFERENCES CARGO(CARGO_ID),
  CONSTRAINT FK_AREA_EN_SOLICITANTE FOREIGN KEY (ID_AREA) REFERENCES AREA (AREA_ID),
  CONSTRAINT FK_CONS_CUR_EN_SOLIC FOREIGN KEY (ID_CONSEJO_CURRICULAR) REFERENCES CONSEJO_CURRICULAR (CONSEJO_CURRICULAR_ID),
  CONSTRAINT FK_PROGR_ACAD_EN_SOLIC FOREIGN KEY (ID_PROGRAMA_ACADEMICO) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID)
);
COMMENT ON TABLE SOLICITANTE IS 'Es la entidad que contiene los datos del solicitante que es el que descubre las necesidades de auxiliares.';
COMMENT ON COLUMN SOLICITANTE.SOLICITANTE_ID IS 'Es la llave primaria de la tabla solicitante';
COMMENT ON COLUMN SOLICITANTE.NOMBRE_SOLICITANTE IS 'Es el nombre del solicitante';
COMMENT ON COLUMN SOLICITANTE.APELLIDO_SOLICITANTE IS 'Es elapellido del solicitante';
COMMENT ON COLUMN SOLICITANTE.TELEFONO_SOLICITANTE IS 'Es el telefono del solicitante';
COMMENT ON COLUMN SOLICITANTE.PASSWORD_SOLICITANTE IS 'Es el password del solicitante para iniciar sesi?n.';
COMMENT ON COLUMN SOLICITANTE.ID_DIRECCION IS 'Es la llave foranea que identifica la direccion del solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_CARGO  IS 'Es la llave foranea que identifica el cargo que ocupa el solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_AREA  IS 'Es la llave foranea que identifica el area a la cual pertenece el solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_CONSEJO_CURRICULAR  IS 'Es la llave foranea que identifica el consejo curricular al cual puede o no pertencer un solicitante';
COMMENT ON COLUMN SOLICITANTE.ID_PROGRAMA_ACADEMICO IS 'Es la llave foranea que identifica el eprograma academico al cual pertenece el solicitante.';

CREATE TABLE JORNADA (
JORNADA_ID VARCHAR2 (20) NOT NULL,
NOMBRE_JORNADA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_JORNADA PRIMARY KEY (JORNADA_ID)
);
COMMENT ON TABLE JORNADA IS 'Es entidad que contiene los datos de la jornada en la cual se desempe?a un director de programa';
COMMENT ON COLUMN JORNADA.JORNADA_ID IS 'Es la llave primara de la tabla jornada';
COMMENT ON COLUMN JORNADA.NOMBRE_JORNADA IS 'Es el nombre de la jornada del programa academico (nocturno, diurno, a distancia).';

CREATE TABLE DIRECTORES (
ID_PROGRAMA VARCHAR2 (20) NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL UNIQUE,
ID_JORNADA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_DIRECTORES PRIMARY KEY (ID_PROGRAMA, ID_JORNADA),
CONSTRAINT FK_PROGRAMA_EN_DIRECTORES FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID),
CONSTRAINT FK_SOLICITANTE_EN_DIRECTORES FOREIGN KEY (ID_SOLICITANTE)REFERENCES SOLICITANTE (SOLICITANTE_ID),
CONSTRAINT FK_JORNADA_EN_DIRECTORES FOREIGN KEY (ID_JORNADA) REFERENCES JORNADA (JORNADA_ID)
);
COMMENT ON TABLE DIRECTORES IS 'Es la entidad puente que contiene los datos de los directores de programa';
COMMENT ON COLUMN DIRECTORES.ID_PROGRAMA IS 'Es la llave foranea que ientifica el programa al cual pertenece el director';
COMMENT ON COLUMN DIRECTORES.ID_SOLICITANTE  IS 'Es la llave foranea que identifica el nombre del director, el cual a su vez puede ser un solicitante';
COMMENT ON COLUMN DIRECTORES.ID_JORNADA IS 'Es la llave foranea que identifica la jornada del programa que dirige el solicitante';

CREATE TABLE AUXILIAR(
AUXILIAR_ID VARCHAR2 (20) NOT NULL,
CODIGO_AUXILIAR VARCHAR2 (20) UNIQUE NOT NULL,
NOMBRE_AUXILIAR VARCHAR2 (35) NOT NULL,
APELLIDO_AUXILIAR VARCHAR2 (35) NOT NULL,
TELEFONO_AUXILIAR VARCHAR2 (20) NOT NULL,
PASSWORD_AUX VARCHAR2(255) NOT NULL,
ID_DIRECCION VARCHAR2 (20) NOT NULL,
ID_PROGRAMA_ACADEMICO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_AUXILIAR PRIMARY KEY (AUXILIAR_ID),
CONSTRAINT FK_DIRECCION_EN_AUXILIAR FOREIGN KEY (ID_DIRECCION) REFERENCES DIRECCION (DIRECCION_ID),
CONSTRAINT FK_PROG_ACAD_EN_AUX FOREIGN KEY (ID_PROGRAMA_ACADEMICO) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID)
);
COMMENT ON TABLE AUXILIAR IS 'Es la entidad que contiene los datos del auxiliar o estudiante que postula o puede observar las convocatorias.';
COMMENT ON COLUMN AUXILIAR.AUXILIAR_ID IS 'Es la llave primaria de la tabla, es distinto al codigo';
COMMENT ON COLUMN AUXILIAR.CODIGO_AUXILIAR IS 'Es la identificacion del auxiliar (cedula o tarjeta de identidad)';
COMMENT ON COLUMN AUXILIAR.NOMBRE_AUXILIAR IS 'Es el nombre del auxiliar';
COMMENT ON COLUMN AUXILIAR.APELLIDO_AUXILIAR IS 'Es el apellido del auxiliar';
COMMENT ON COLUMN AUXILIAR.TELEFONO_AUXILIAR IS 'Es el telefono del auxiliar';
COMMENT ON COLUMN AUXILIAR.PASSWORD_AUX IS 'Es el password del auxiliar para iniciar sesi?n.';
COMMENT ON COLUMN AUXILIAR.ID_DIRECCION IS 'Es el la llave foranea que identifica la direccion que tiene el auxiliar';
COMMENT ON COLUMN AUXILIAR.ID_PROGRAMA_ACADEMICO IS 'Es la llave foranea que identifica el programa acad?mico al que pertenece el auxiliar';

CREATE TABLE TIPO_REQUISITO (
TIPO_REQUISITO_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_TIPO_REQUISITO VARCHAR2 (255) NOT NULL,
CONSTRAINT PK_TIPO_REQUISITO PRIMARY KEY (TIPO_REQUISITO_ID)
);
COMMENT ON TABLE TIPO_REQUISITO IS 'Es la entidad que contiene los datos de los tipos de requisitos de una convocatoria (general, especificos)';
COMMENT ON COLUMN TIPO_REQUISITO.TIPO_REQUISITO_ID IS 'Es la llave primaria de la tabla tipo requisito.';
COMMENT ON COLUMN TIPO_REQUISITO.DESCRIPCION_TIPO_REQUISITO IS 'Es la descripcion del tipo de requisito.';

CREATE TABLE REQUISITO (
REQUISITO_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_REQUISITO VARCHAR2 (255) NOT NULL,
ID_TIPO_REQUISITO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_REQUISITO PRIMARY KEY (REQUISITO_ID),
CONSTRAINT FK_TIPO_REQUISITO_EN_REQUISITO FOREIGN KEY (ID_TIPO_REQUISITO) REFERENCES TIPO_REQUISITO(TIPO_REQUISITO_ID)
); 
COMMENT ON TABLE REQUISITO IS 'En la entidad que contiene los datos de los requisitos necesarios de una convocatoria.';
COMMENT ON COLUMN REQUISITO.REQUISITO_ID IS 'Es la llave primaria de la tabla requisito';
COMMENT ON COLUMN REQUISITO.DESCRIPCION_REQUISITO IS 'Es la desripcion del requisito';
COMMENT ON COLUMN REQUISITO.ID_TIPO_REQUISITO IS 'Es la llave foranea que identifica el tipo de requisito al cual pertenece un requisito.';

CREATE TABLE SOLICITUD_AUXILIARES(
SOLICITUD_AUXILIARES_ID VARCHAR2 (20) NOT NULL,
CANTIDAD_AUXILIARES NUMBER (2,0) NOT NULL,
CANTIDAD_HORAS NUMBER (3,0) NOT NULL,
DESC_SOLICITUD_AUXILIARES VARCHAR (255) NOT NULL,
FECHA_CREACION DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SOLICITUD_AUXILIARES PRIMARY KEY (SOLICITUD_AUXILIARES_ID),
CONSTRAINT FK_SOLIC_EN_SOLIC_AUX FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);
COMMENT ON TABLE SOLICITUD_AUXILIARES IS 'Es la entidad que contiene los datos de las solicitudes de auxiliares.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.SOLICITUD_AUXILIARES_ID IS 'Es la llave primaria de la tabla colicitud auxiliares';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.CANTIDAD_AUXILIARES IS 'Es la cantidad de auxiliares requeridos.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.CANTIDAD_HORAS IS 'Es la cantiidad de horas requeridas por cada auxiliar.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.DESC_SOLICITUD_AUXILIARES IS 'Es la descripcion de una solicitud de auxiliiares.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.FECHA_CREACION IS 'Es la fecha de creacion de la solicitud.';
COMMENT ON COLUMN SOLICITUD_AUXILIARES.ID_SOLICITANTE IS 'Es la llave foranea que identifica el solicitante que crea la solicitud.';

CREATE TABLE SOL_AUXILIARES_REQUISITOS(
ID_REQUISITO VARCHAR2 (20) NOT NULL,
ID_SOLICITUD_AUXILIARES VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SOL_AUX_REQ PRIMARY KEY (ID_REQUISITO, ID_SOLICITUD_AUXILIARES),
CONSTRAINT FK_REQ_EN_SOL_AUX_REQU FOREIGN KEY (ID_REQUISITO) REFERENCES REQUISITO (REQUISITO_ID),
CONSTRAINT FK_SOL_AUX_EN_SOL_AUX_REQ FOREIGN KEY (ID_SOLICITUD_AUXILIARES) REFERENCES SOLICITUD_AUXILIARES(SOLICITUD_AUXILIARES_ID)
);
COMMENT ON TABLE SOL_AUXILIARES_REQUISITOS IS 'Es la entidad puente entre las solicitudes de auxiliares y los requisitos.';
COMMENT ON COLUMN SOL_AUXILIARES_REQUISITOS.ID_REQUISITO IS 'Es la llave foranea que identifica un requisito dentro de la solicitud.';
COMMENT ON COLUMN SOL_AUXILIARES_REQUISITOS.ID_SOLICITUD_AUXILIARES IS 'Es la llave foranea que identifica la solicitud de auxiliares.';

CREATE TABLE TIPO_AUXILIAR (
TIPO_AUXILIAR_ID VARCHAR2 (20) NOT NULL,
DESCRIPCION_TIPO_AUXILIAR VARCHAR2 (255) NOT NULL,
CONSTRAINT PK_TIPO_AUXILIAR PRIMARY KEY (TIPO_AUXILIAR_ID)
);
COMMENT ON TABLE TIPO_AUXILIAR IS 'Es la entidad que contiene los datos del tipo auxiliar (docencia, administrativos, monitor... entre otros que se requieran).';
COMMENT ON COLUMN TIPO_AUXILIAR.TIPO_AUXILIAR_ID IS 'Es la llave primaria de la tabla Tipo auxiliar';
COMMENT ON COLUMN TIPO_AUXILIAR.DESCRIPCION_TIPO_AUXILIAR IS 'Es la descripci?n de la tabla tipo auxiliar';

CREATE TABLE CONVOCATORIA (
CONVOCATORIA_ID VARCHAR2 (20) NOT NULL,
INFO_ADICIONAL_CONVOCATORIA VARCHAR2 (255) NOT NULL,
FECHA_CREACION DATE NOT NULL,
FECHA_APERTURA DATE NOT NULL,
FECHA_CIERRE DATE NOT NULL,
FECHA_PRUEBA DATE,
ID_TIPO_AUXILIAR VARCHAR (20) NOT NULL,
ID_PROGRAMA_ACADEMICO VARCHAR2 (20) NOT NULL,
ID_SOLICITUD_AUXILIARES VARCHAR (20) UNIQUE NOT NULL,
CONSTRAINT PK_CONVOCATORIA PRIMARY KEY (CONVOCATORIA_ID),
CONSTRAINT FK_TIPO_AUXILIAR_EN_CONV FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR (TIPO_AUXILIAR_ID),
CONSTRAINT FK_PROG_ACAD_EN_CONV FOREIGN KEY (ID_PROGRAMA_ACADEMICO) REFERENCES PROGRAMA_ACADEMICO (PROGRAMA_ACADEMICO_ID),
CONSTRAINT FK_SOL_AUX_EN_CONV FOREIGN KEY (ID_SOLICITUD_AUXILIARES) REFERENCES SOLICITUD_AUXILIARES (SOLICITUD_AUXILIARES_ID)
);
COMMENT ON TABLE CONVOCATORIA IS 'Es la entidad que contiene los datos de las convocatorias';
COMMENT ON COLUMN CONVOCATORIA.CONVOCATORIA_ID IS 'Es la llave primaria de la tabla convocatoria';
COMMENT ON COLUMN CONVOCATORIA.INFO_ADICIONAL_CONVOCATORIA IS 'Es la informacion adicional perinente a la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_CREACION IS 'Es la fecha de creacion en la base de datos de la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_APERTURA IS 'Es la fecha de apertura de la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_CIERRE IS 'Es la fecha de cierre de la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.FECHA_PRUEBA IS 'Es la fecha de prueba de la convocatoria, si aplica o no, puede ser null';
COMMENT ON COLUMN CONVOCATORIA.ID_TIPO_AUXILIAR IS 'Es la llave foranea que identifica el tipo de auxiliar que por el cual se abre la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.ID_PROGRAMA_ACADEMICO IS 'Es la llave foranea que identifica el programa academico que necesita el auxiliar por el cual abre la convocatoria';
COMMENT ON COLUMN CONVOCATORIA.ID_SOLICITUD_AUXILIARES IS 'Es la llave foranea que identifica la solicitud relacionada a la convocatoria';

CREATE TABLE CONVOCATORIA_REQUISITOS (
ID_REQUISITOS VARCHAR2 (20) NOT NULL,
ID_CONVOCATORIA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_CONVOCATORIA_REQUISITOS PRIMARY KEY (ID_REQUISITOS, ID_CONVOCATORIA),
CONSTRAINT FK_REQ_EN_CONV_REQ FOREIGN KEY (ID_REQUISITOS) REFERENCES REQUISITO (REQUISITO_ID),
CONSTRAINT FK_CONV_EN_CONV_REQ FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA (CONVOCATORIA_ID)
);
COMMENT ON TABLE CONVOCATORIA_REQUISITOS IS 'Es la entidad puente que contiene los datos de convocatoria y requisitos.';
COMMENT ON COLUMN CONVOCATORIA_REQUISITOS.ID_REQUISITOS IS 'Es la llave foranea que identifica los requisitos generales o especificos necesarios en la convocatoria';
COMMENT ON COLUMN CONVOCATORIA_REQUISITOS.ID_CONVOCATORIA IS 'Es la llave foranea que identifica la convocatoria a la que se le van a aplicar los requisitos';

CREATE TABLE EVALUACION_AUXILIARES (
EVALUACION_AUXILIARES_ID VARCHAR2 (20) NOT NULL,
DESC_EVALUACION_AUXILIARES VARCHAR2 (255) NOT NULL,
FECHA_CREACION DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,
ID_CONVOCATORIA VARCHAR2 (20) UNIQUE NOT NULL,
CONSTRAINT PK_EVALUACION_AUXILIARES PRIMARY KEY (EVALUACION_AUXILIARES_ID),
CONSTRAINT FK_SOL_EN_EVAL_AUX FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID),
CONSTRAINT FK_CONV_EN_EVA_AUX FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA (CONVOCATORIA_ID)
);
COMMENT ON TABLE EVALUACION_AUXILIARES IS 'Es la entidad que contiene los datos de una evaluacion';
COMMENT ON COLUMN EVALUACION_AUXILIARES.EVALUACION_AUXILIARES_ID IS 'Es la llave primaria de la tabla evaluacion';
COMMENT ON COLUMN EVALUACION_AUXILIARES.DESC_EVALUACION_AUXILIARES IS 'Es la descripcion de la evaluacion';
COMMENT ON COLUMN EVALUACION_AUXILIARES.FECHA_CREACION IS 'Es la fecha de creacion de la evaluacion';
COMMENT ON COLUMN EVALUACION_AUXILIARES.ID_SOLICITANTE IS 'Es la llave foranea que identifica el solicitante dentro de la evaluacion';
COMMENT ON COLUMN EVALUACION_AUXILIARES.ID_CONVOCATORIA IS 'Es la llave foranea que identifica la convocatoria a la cual pertenece la evaluacion';

CREATE TABLE SELECCION_AUXILIARES (
CALIFICACION NUMBER (2,1) NOT NULL,
ESTADO NUMBER (1,0) NOT NULL,
PROMEDIO NUMBER (2,1) NOT NULL,
ID_AUXILIARES VARCHAR2 (20) NOT NULL,
ID_EVALUACION_AUXILIARES VARCHAR (20),
CONSTRAINT PK_SELECCION_AUXILIARES PRIMARY KEY (ID_AUXILIARES, ID_EVALUACION_AUXILIARES),
CONSTRAINT FK_AUX_EN_SEL_AUX FOREIGN KEY (ID_AUXILIARES) REFERENCES AUXILIAR (AUXILIAR_ID),
CONSTRAINT FK_EVAL_AUX_EN_SEL_AUX FOREIGN KEY (ID_EVALUACION_AUXILIARES) REFERENCES EVALUACION_AUXILIARES (EVALUACION_AUXILIARES_ID)
);
COMMENT ON TABLE SELECCION_AUXILIARES IS 'Es la entidad puente que contiene los datos de los auxiliares y la evaluacion';
COMMENT ON COLUMN SELECCION_AUXILIARES.CALIFICACION IS 'Es la calificacion de la prueba practicada, puede ser nula sin no aplica prueba';
COMMENT ON COLUMN SELECCION_AUXILIARES.ESTADO IS 'Es estado de la prueba practicada a los auxiliares';
COMMENT ON COLUMN SELECCION_AUXILIARES.PROMEDIO IS 'Es el promedio del auxiliar';
COMMENT ON COLUMN SELECCION_AUXILIARES.ID_AUXILIARES IS 'Es la llave foranea que identifica el auxiliar dentro de la lista de seleccion';
COMMENT ON COLUMN SELECCION_AUXILIARES.ID_EVALUACION_AUXILIARES IS 'Es la llave foranea que identifica la evaluacion relacionada con el auxiliar';

CREATE TABLE HORARIO_ACTIVIDADES (
HORARIO_ACTIVIDADES_ID VARCHAR2 (20) NOT NULL,
FECHA_CREACION_HORARIO_ACTIV DATE NOT NULL,
ID_TIPO_AUXILIAR VARCHAR2 (20),
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_HORARIO_ACTIVIDADES PRIMARY KEY (HORARIO_ACTIVIDADES_ID),
CONSTRAINT FK_TIPO_AUX_EN_HOR_ACT FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR (TIPO_AUXILIAR_ID), 
CONSTRAINT FK_ID_AUX_EN_HOR_ACT FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUXILIAR_ID)
);
COMMENT ON TABLE HORARIO_ACTIVIDADES IS 'Es la entidad que contiene los datos del horario del auxiliar.';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.HORARIO_ACTIVIDADES_ID  IS 'Es la llave primaria de la tabla horario auxiliar.';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.FECHA_CREACION_HORARIO_ACTIV IS 'Es la fecha de craci?n del horario de actividades';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.ID_TIPO_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla tipo auxiliar';
COMMENT ON COLUMN HORARIO_ACTIVIDADES.ID_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla auxiliar';

CREATE TABLE FECHA_HORARIO (
FECHA_HORARIO_ID VARCHAR2 (20) NOT NULL,
FECHA_FECHA_HORARIO DATE NOT NULL,
ID_HORARIO_ACTIVIDADES VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_FECHA_HORARIO PRIMARY KEY (FECHA_HORARIO_ID),
CONSTRAINT FK_HOR_ACT_EN_FEC_HOR FOREIGN KEY (ID_HORARIO_ACTIVIDADES) REFERENCES HORARIO_ACTIVIDADES (HORARIO_ACTIVIDADES_ID)
);
COMMENT ON TABLE FECHA_HORARIO  IS 'Es la entidad que contiene los datos de la fecha de el horario (dia que realiza la actividad).';
COMMENT ON COLUMN FECHA_HORARIO.FECHA_HORARIO_ID IS 'Es la llave primaria de la tabla fecha horario.';
COMMENT ON COLUMN FECHA_HORARIO.FECHA_FECHA_HORARIO IS 'Es la fecha de realizacion de las actividades';
COMMENT ON COLUMN FECHA_HORARIO.ID_HORARIO_ACTIVIDADES IS 'Es el campo que identifica la llave foranea de la tabla horario de actividades.';

CREATE TABLE HORA (
HORA_INICIO VARCHAR2 (20) NOT NULL,
HORA_FIN VARCHAR2 (20) NOT NULL,
ID_FECHA_HORARIO VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_HORA PRIMARY KEY (HORA_INICIO,ID_FECHA_HORARIO),
CONSTRAINT FK_FECHA_HORARIO_EN_HORA FOREIGN KEY (ID_FECHA_HORARIO) REFERENCES FECHA_HORARIO (FECHA_HORARIO_ID)
);
COMMENT ON TABLE HORA IS 'Es la entidad que contiene las horas asignadas o concordadas con el auxiliar para realizar las actividades.';
COMMENT ON COLUMN HORA.HORA_INICIO IS 'Es el campo que identifica la hora de unicio de las actividades.';
COMMENT ON COLUMN HORA.HORA_FIN IS 'Es el campo que identifica la hora de finalizaci?n de las actividades.';
COMMENT ON COLUMN HORA.ID_FECHA_HORARIO IS 'Es el campo que identifica la llave foranea de la tabla fecha horario.';

CREATE TABLE CUMPLIMIENTO_ACTIVIDADES(
CUMP_ACT_ID VARCHAR2 (20) NOT NULL,
DESC_CUMP_ACT VARCHAR2 (255) NOT NULL,
FECHA_CREACION_CUMP_ACT DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_CUMP_ACT PRIMARY KEY (CUMP_ACT_ID),
CONSTRAINT FK_SOL_EN_CUMP_ACT FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);
COMMENT ON TABLE CUMPLIMIENTO_ACTIVIDADES IS 'Es la entidad que contiene el cumplimiento de las actividades del auxiliar.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.CUMP_ACT_ID IS 'Es la llave primaria de la tabla cumplimieto actividades.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.DESC_CUMP_ACT IS 'Es el campo que identifica a la descripcion del cumplimiento de activiades.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.FECHA_CREACION_CUMP_ACT IS 'Es el campo que identifica a la fecha de creaci?n del cumplimiento.';
COMMENT ON COLUMN CUMPLIMIENTO_ACTIVIDADES.ID_SOLICITANTE IS 'Es el campo que identifica la llave foranea de la tabla solicitante.';

CREATE TABLE AUX_CUMPLIMIENTO_ACTIVIDADES(
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_CUMPLIMIENTO_ACTIVIDADES VARCHAR2 (20) NOT NULL,
ID_TIPO_AUXILIAR VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_AUX_CUMP_ATIVIDADES PRIMARY KEY (ID_AUXILIAR,ID_CUMPLIMIENTO_ACTIVIDADES),
CONSTRAINT FK_AUX_EN_AUX_CUMP_ACT FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUXILIAR_ID),
CONSTRAINT FK_CUMP_ACT_EN_AUX_CUMP_ACT FOREIGN KEY (ID_CUMPLIMIENTO_ACTIVIDADES) REFERENCES CUMPLIMIENTO_ACTIVIDADES (CUMP_ACT_ID),
CONSTRAINT FK_TIPO_AUX_EN_AUX_CUMP_ACT FOREIGN KEY (ID_TIPO_AUXILIAR) REFERENCES TIPO_AUXILIAR (TIPO_AUXILIAR_ID)
);
COMMENT ON TABLE AUX_CUMPLIMIENTO_ACTIVIDADES IS 'Es la entidad PUENTE que representa el auxiliar con el cumplimiento de actividades.';
COMMENT ON COLUMN AUX_CUMPLIMIENTO_ACTIVIDADES.ID_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla auxiliar.';
COMMENT ON COLUMN AUX_CUMPLIMIENTO_ACTIVIDADES.ID_CUMPLIMIENTO_ACTIVIDADES IS 'Es el campo que identifica la llave foranea de la tabla cumplimiento de actividades.';
COMMENT ON COLUMN AUX_CUMPLIMIENTO_ACTIVIDADES.ID_TIPO_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla tipo de auxiliar.';

CREATE TABLE RES_AUXILIARES_SELECCIONADOS(
RES_AUX_SEL_ID VARCHAR2 (20) NOT NULL,
DESC_RES_AUX_SEL VARCHAR2 (255) NOT NULL,
FECHA_CREA_RES_AUX_SEL DATE NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_RES_AUX_SELECCIONADOS PRIMARY KEY (RES_AUX_SEL_ID),
CONSTRAINT FK_SOL_EN_RES_AUX_SEL FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);
COMMENT ON TABLE RES_AUXILIARES_SELECCIONADOS IS 'Es la entidad que representa la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RES_AUXILIARES_SELECCIONADOS.RES_AUX_SEL_ID IS 'Es la llave primaria de la tabla resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RES_AUXILIARES_SELECCIONADOS.DESC_RES_AUX_SEL IS 'Es el campo que identifica a la descripcion de la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RES_AUXILIARES_SELECCIONADOS.FECHA_CREA_RES_AUX_SEL IS 'Es el campo que identifica a la fecha decreacion de la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN RES_AUXILIARES_SELECCIONADOS.ID_SOLICITANTE IS 'Es el campo que identifica la llave foranea de la tabla tipo de solicitante.';

CREATE TABLE DETALLE_RESOLUCION(
PROM_AUX_DET_RES NUMBER (2,1)  NOT NULL,
VALOR_PAGAR_DETALLE_RES NUMBER (10,0) NOT NULL,
CANT_HORAS_DETALLE_RES NUMBER (5,0) NOT NULL,
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_RES_AUX_SEL VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_DETALLE_RESOLUCION PRIMARY KEY (ID_AUXILIAR, ID_RES_AUX_SEL),
CONSTRAINT FK_AUX_EN_DET_RES FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUXILIAR_ID),
CONSTRAINT FK_RES_AUX_SEL_EN_DET_RES FOREIGN KEY (ID_RES_AUX_SEL) REFERENCES RES_AUXILIARES_SELECCIONADOS (RES_AUX_SEL_ID)
);
COMMENT ON TABLE DETALLE_RESOLUCION IS 'Es la entidad PUENTE que representa la resolucion de auxiliares seleccionados.';
COMMENT ON COLUMN DETALLE_RESOLUCION.PROM_AUX_DET_RES IS 'Es el campo que identifica el promedio de los auxiliares seleccionados.';
COMMENT ON COLUMN DETALLE_RESOLUCION.VALOR_PAGAR_DETALLE_RES IS 'Es el campo que identifica el valor a pagar en el detalle de resolucion.';
COMMENT ON COLUMN DETALLE_RESOLUCION.CANT_HORAS_DETALLE_RES IS 'Es el campo que identifica la cantidad de horas en el detalle de resolucion.';
COMMENT ON COLUMN DETALLE_RESOLUCION.ID_AUXILIAR  IS 'Es el campo que identifica la llave foranea de la tabla auxiliar.';
COMMENT ON COLUMN DETALLE_RESOLUCION.ID_RES_AUX_SEL IS 'Es el campo que identifica la llave foranea de la tabla de resolucion de auxiliares seleccionados.';

CREATE TABLE INCONFORMIDAD_AUXILIARES(
INCONFORMIDAD_AUXILIARES_ID VARCHAR2 (20) NOT NULL,
FECHA_CREA_INC_AUX DATE NOT NULL,
DESC_INC_AUX VARCHAR2 (255) NOT NULL,
CONSTRAINT PK_INCONFORMIDAD_AUXILIARES PRIMARY KEY (INCONFORMIDAD_AUXILIARES_ID)
);
COMMENT ON TABLE INCONFORMIDAD_AUXILIARES IS 'Es la entidad que representa la inconformidad de los auxiliares.';
COMMENT ON COLUMN INCONFORMIDAD_AUXILIARES.INCONFORMIDAD_AUXILIARES_ID IS 'Es llave primaria que identifica  la inconformidad de los auxiliares.';
COMMENT ON COLUMN INCONFORMIDAD_AUXILIARES.FECHA_CREA_INC_AUX IS 'Es el campo que identifica a la fecha de creaci?n inconformidad de los auxiliares.';
COMMENT ON COLUMN INCONFORMIDAD_AUXILIARES.DESC_INC_AUX IS 'Es el campo que identifica a la descripci?n  de inconformidad de los auxiliares.';

CREATE TABLE INC_AUX_AUXILIAR(
ID_INCONFORMIDAD_AUXILIARES VARCHAR2 (20) NOT NULL,
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_SOLICITANTE VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_INC_AUX_AUXILIAR PRIMARY KEY (ID_INCONFORMIDAD_AUXILIARES, ID_AUXILIAR),
CONSTRAINT FK_INC_AUX_EN_INC_AUX_AUX FOREIGN KEY (ID_INCONFORMIDAD_AUXILIARES) REFERENCES INCONFORMIDAD_AUXILIARES (INCONFORMIDAD_AUXILIARES_ID),
CONSTRAINT FK_AUX_EN_INC_AUX_AUX FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUXILIAR_ID),
CONSTRAINT FK_SOL_EN_INC_AUX_AUX FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE (SOLICITANTE_ID)
);
COMMENT ON TABLE INC_AUX_AUXILIAR IS 'Es la entidad PUENTE que representa la inconformidad de auxiliares con auxiliares.';
COMMENT ON COLUMN INC_AUX_AUXILIAR.ID_INCONFORMIDAD_AUXILIARES IS 'Es el campo que identifica la llave foranea de la tabla inconformidad de auxiliares.';
COMMENT ON COLUMN INC_AUX_AUXILIAR.ID_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla auxiliar.';
COMMENT ON COLUMN INC_AUX_AUXILIAR.ID_SOLICITANTE IS 'Es el campo que identifica la llave foranea de la tabla solicitante.';

CREATE TABLE INSCRIPCION_CONVOCATORIA(
FECHA_INSCRIPCION_CONVOCATORIA  DATE NOT NULL,
ID_AUXILIAR VARCHAR2 (20) NOT NULL,
ID_CONVOCATORIA VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_INSCRIPCION_CONVOCATORIA PRIMARY KEY (ID_AUXILIAR, ID_CONVOCATORIA),
CONSTRAINT FK_AUX_EN_INSC_CONV FOREIGN KEY (ID_AUXILIAR) REFERENCES AUXILIAR (AUXILIAR_ID),
CONSTRAINT FK_CONV_EN_INSC_CONV FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA (CONVOCATORIA_ID)
);
COMMENT ON TABLE INSCRIPCION_CONVOCATORIA IS 'Es la entidad PUENTE que representa la inscripcion a la convocatoria (Convocatoria-Auxiliares).';
COMMENT ON COLUMN INSCRIPCION_CONVOCATORIA.FECHA_INSCRIPCION_CONVOCATORIA IS 'Es la fecha de inscripcion a la convocatoria.';
COMMENT ON COLUMN INSCRIPCION_CONVOCATORIA.ID_AUXILIAR IS 'Es el campo que identifica la llave foranea de la tabla auxiliar.';
COMMENT ON COLUMN INSCRIPCION_CONVOCATORIA.ID_CONVOCATORIA  IS 'Es el campo que identifica la llave foranea de la tabla convocatoria.';
